# Generated by Django 5.2.5 on 2026-01-30 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Web Development', 'Web Development'), ('Mobile App', 'Mobile App'), ('AI/ML', 'AI/ML'), ('Design', 'Design'), ('Data Science', 'Data Science'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('budget_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Hourly Rate')], default='fixed', max_length=20)),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('skills_required', models.TextField(help_text='Comma-separated list of skills')),
                ('min_skill_score', models.IntegerField(default=0, help_text='Minimum SkillForge Score required to apply')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('draft', 'Draft')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='accounts.clientprofile')),
            ],
        ),
    ]
