# Generated by Django 5.2.5 on 2026-01-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalityquestion',
            name='test',
        ),
        migrations.RemoveField(
            model_name='personalityattempt',
            name='test',
        ),
        migrations.AddField(
            model_name='personalityattempt',
            name='answers',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='personalityattempt',
            name='learning_level',
            field=models.CharField(choices=[('fast', 'Fast'), ('average', 'Average'), ('slow', 'Slow')], max_length=20),
        ),
        migrations.DeleteModel(
            name='PersonalityOption',
        ),
        migrations.DeleteModel(
            name='PersonalityQuestion',
        ),
        migrations.DeleteModel(
            name='PersonalityTest',
        ),
    ]
